#Nats Settings
nats:
    spring:
        server: "nats://messaging-server:4222" 
spring:
  cloud:
    stream:
        bindings:
            input:
                destination: zeebe-export  
                binder: nats
            output:
                destination: requestreply-topic
                binder: nats                
  jpa:
    show-sql: false
    properties:
      eclipselink:
        logging:
          logger: "hu.dpc.phee.operator.config.EclipselinkLogger"
    open-in-view: false

datasource:
  common:
    protocol: "jdbc"
    subprotocol: "mysql"
    driverclass_name: "com.mysql.cj.jdbc.Driver"
  core:
    port: 3306
    host: "operations-mysql"
    schema: "tenants"
    username: "root"
    password: "mysql"

server:
  port: 8000

bpmn:
  transfer-type: "TRANSFER"
  transaction-request-type: "TRANSACTION-REQUEST"
  batch-type: "BATCH"
  incoming-direction: "INCOMING"
  outgoing-direction: "OUTGOING"
  processes:
    - id: "PayeeQuoteTransfer"
      direction: "${bpmn.incoming-direction}"
      type: "${bpmn.transfer-type}"
    - id: "PayerTransactionRequest"
      direction: "${bpmn.incoming-direction}"
      type: "${bpmn.transaction-request-type}"
    - id: "PayerFundTransfer"
      direction: "${bpmn.outgoing-direction}"
      type: "${bpmn.transfer-type}"
    - id: "PayeeTransactionRequest"
      direction: "${bpmn.outgoing-direction}"
      type: "${bpmn.transaction-request-type}"
    - id: "transferProcess"
      direction: "UNKNOWN"
      type: "${bpmn.transfer-type}"
    - id: "bulk_processor"
      direction: "UNKNOWN"
      type: "${bpmn.batch-type}"
    - id: "international_remittance_payee_process"
      direction: "${bpmn.outgoing-direction}"
      type: "${bpmn.transfer-type}"
    - id: "international_remittance_payer_process"
      direction: "${bpmn.outgoing-direction}"
      type: "${bpmn.transfer-type}"
    - id: "mpesa_flow"
      direction: "${bpmn.incoming-direction}"
      type: "${bpmn.transaction-request-type}"
    - id: "mpesa_flow_roster"
      direction: "${bpmn.incoming-direction}"
      type: "${bpmn.transaction-request-type}"
    - id: "mpesa_flow-paygops"
      direction: "${bpmn.incoming-direction}"
      type: "${bpmn.transaction-request-type}"
    - id: "phee_same_bank_same_owner"
      direction: "${bpmn.outgoing-direction}"
      type: "${bpmn.transfer-type}"

logging:
  level:
    ROOT: ERROR
